name: fbla_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  simple_gradient_text: 1.3.0
  gradient_borders: 1.0.1
  flutter_svg_provider: 1.0.7
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_database: ^11.3.4
  firebase_app_installations: ^0.3.2+4
  firebase_in_app_messaging: ^0.8.1+4
  sign_in_with_apple: ^6.1.4
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
