// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUjwM9UcrV35aWa5KXxFoQofCYtB9vr40',
    appId: '1:335054872141:android:bfb01bad56bf51f8654604',
    messagingSenderId: '335054872141',
    projectId: 'fbla-mobile-app-dev-d426f',
    storageBucket: 'fbla-mobile-app-dev-d426f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6aPfpViW9wQUMK3FipwGpNvVQ-j0Vffg',
    appId: '1:335054872141:ios:83029e468304ab65654604',
    messagingSenderId: '335054872141',
    projectId: 'fbla-mobile-app-dev-d426f',
    storageBucket: 'fbla-mobile-app-dev-d426f.firebasestorage.app',
    androidClientId: '335054872141-fbi78qdulp4giqhqp567t6uhm6c9jqji.apps.googleusercontent.com',
    iosClientId: '335054872141-21rnq367aqp6i6p8jckhe4itk8u5pt0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.fblaMobileApp',
  );

}